INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/autenticacao.m4a', 'audio/x-m4a', 1463);
INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/typescript.m4a', 'audio/x-m4a', 1772);
INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/comunidade.m4a', 'audio/x-m4a', 2677);
INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/lider-desenvolvimento.m4a', 'audio/x-m4a', 2917);
INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/design.m4a', 'audio/x-m4a', 2715);
INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/jose-valim.m4a', 'audio/x-m4a', 4936);
INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/clean.m4a', 'audio/x-m4a', 5044);
INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/microservicos.m4a', 'audio/x-m4a', 5506);
INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/funcional.m4a', 'audio/x-m4a', 4237);
INSERT INTO tb_file (url, type, duration) VALUES ('https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/audios/opensource.m4a', 'audio/x-m4a', 3981);

INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('FalaDev #21 - Estratégias de autenticação, JWT, OAuth, qual usar?', 'Diego Fernandes, Higo Ribeiro e Guilherme Pellizzetti', TIMESTAMP WITH TIME ZONE '2020-04-09T20:00:00Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/autenticacao.jpg', '<p>Três programadores conversam sobre estratégia de autenticação.</p><p>Vamos discutir quais aspectos você deve considerar na hora de fazer a sua escolha.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso.</p>', 1);
INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('FalaDev #22 - TypeScript vale a pena? JavaScript perde sentido?', 'Diego Fernandes, Mayk Brito e João Pedro', TIMESTAMP WITH TIME ZONE '2020-05-04T14:49:35Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/typescript.jpg', '<p>Três programadores conversam sobre TypeScript.</p><p>Vamos discutir a usabilidade e as previsões da linguagem no cenário da programação.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso.</p>', 2);
INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('FalaDev #23 | O que comunidades têm a ver com tecnologia?', 'Diego Fernandes, Isabela Castilho e João Inácio', TIMESTAMP WITH TIME ZONE '2020-10-16T13:00:00Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/comunidade.jpg', '<p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos três profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat onde conversamos sobre diversos assuntos que importam para a sua carreira dev.</p><p>Nesse primeiro episódio da nova temporada, Diego Fernandes se reúne com Isabela Castilho e João Inácio Neto (Biro) para discutir sobre comunidades e o impacto que elas exercem na carreira de devs em busca do próximo nível. Afinal, O que é uma comunidade e o que tem a ver com tecnologia?</p>', 3);
INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('Faladev #24 | Como virar líder de desenvolvimento?', 'Diego Fernandes, João Paulo e Cleiton Souza', TIMESTAMP WITH TIME ZONE '2020-10-23T14:00:00Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/lider-desenvolvimento.jpg', '<p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos três profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat onde conversamos sobre diversos assuntos que importam para a sua carreira dev. Nesse episódio, Diego Fernandes se reúne com Cleiton Souza e João Paulo de Magalhães para discutir sobre liderança, considerando aspectos profissionais, técnicos e até mesmo emocionais, o que envolve ser um líder de desenvolvimento? Afinal, o que é um líder de desenvolvimento?</p>', 4);
INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('Faladev #25 | O que é UX/UI?', 'Diego Fernandes, Tiago Luchtenberg e Thainan Librelon', TIMESTAMP WITH TIME ZONE '2020-10-30T14:00:00Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/design.jpg', '<p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos três profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat onde conversamos sobre diversos assuntos que importam para a sua carreira dev.</p><p>Nesse episódio, Diego Fernandes se reúne com Thainan Librelon e Tiago Luchtenberg para discutir sobre: Desenvolvedor pode fazer o trabalho do UI/UX, qual impacto? Qual é o momento ideal pra ter pessoas especializadas em UX e UI? E afinal, o que é UI e o que é UX?</p>', 5);
INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('Faladev #26 | Especial: entrevista exclusiva com José Valim, criador da linguagem Elixir', 'Diego Fernandes e José Valim', TIMESTAMP WITH TIME ZONE '2020-12-04T15:00:00Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/josevalim.jpg', '<p>Nesta edição especial de final de temporada tivemos a oportunidade de ter uma conversa com José Valim, dev brasileiro que criou a linguagem de programação Elixir — utilizada internacionalmente em diversas tecnologias, incluindo Discord e Pinterest.</p><p>O assunto da semana girou em diversos processos envolvidos na criação de uma linguagem nova, que propõe ser uma alternativa eficiente no mercado da tecnologia.</p><p>Além de tudo isso, Valim pôde falar de muito código e sobre a sua jornada e experiência em criar uma comunidade ativa por trás do open source.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos três profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original da Rocketseat onde conversamos sobre diversos assuntos que importam para a sua carreira dev.</p>', 6);
INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('Faladev #27 | Aplicação de arquiteturas MVC e CA na prática', 'Diego Fernandes, Dani Leão, Otávio Lemos e Rodrigo Branas', TIMESTAMP WITH TIME ZONE '2020-12-08T14:00:00Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/clean.jpg', '<p>Diego Fernandes e Daniele Evangelista receberam Otávio Lemos e Rodrigo Branas para bater um papo sobre arquiteturas modernas de desenvolvimento, aplicadas na indústria da tecnologia.</p><p>Quais são os fundamentos, os princípios e a importância de debater arquiteturas neste ecossistema?</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat.  Ficha técnica Hosts: Diego Fernandes e Daniele Leão Evangelista Convidados: Otávio Lemos  e Rodrigo Branas Roteiro: Felipe Buzzi, Beatriz Clasen e Thiago Marinho Edição: Thiago Santana Produção: Leonardo Minatti</p>', 7);
INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('Faladev #28 | Por trás de barreiras e soluções propostas por micro-serviços', 'Diego Fernandes, Dani Leão, Wesley Williams e Lucas Santos', TIMESTAMP WITH TIME ZONE '2021-01-08T13:00:00Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/microservicos.jpg', '<p>Os desenvolvedores Wesley Willians e Lucas Santos foram convidados para este Faladev para ter uma conversa sobre o que são micro-serviços e quais são os desafios e as barreiras de sua aplicação.</p><p>Nessa edição, Diego Fernandes e Daniele Evangelista guiam a conversa levantando tópicos e questionamentos relevantes sobre o assunto.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat.  #programação #rocketseat #programador #programador', 8);
INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('Faladev #29 | Duas perspectivas diferentes na mesa: uma conversa sobre PF e OOP', 'Diego Fernandes, Dani Leão, Laura Beatris e Rafael Camarda', TIMESTAMP WITH TIME ZONE '2021-01-15T13:00:00Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/funcional.jpg', '<p>Diego e Dani receberam Laura Beatris e Rafael Camarda na mesa do Faladev para conversarem sobre programação funcional e programação orientada a objetos.</p><p>Análises de mercado, conceitos na prática e desafios na adoção de qualquer método de desenvolvimento. Tudo isso numa conversa dinâmica e relevante para nosso público.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat.</p>\n', 9);
INSERT INTO tb_episodes (title, members, published_at, thumbnail, description, file_id) VALUES ('Faladev #30 | A importância da contribuição em Open Source', 'Diego Fernandes, João Pedro, Diego Haz e Bruno Lemos', TIMESTAMP WITH TIME ZONE '2021-01-22T16:35:40Z', 'https://storage.googleapis.com/golden-wind/nextlevelweek/05-podcastr/opensource.jpg', '<p>Nesse episódio do Faladev, Diego Fernandes se reúne com João Pedro Schmitz, Bruno Lemos e Diego Haz, para discutir sobre a importância da contribuição open source e quais desafios circulam na comunidade.</p><p>A gente passa a maior parte do tempo escrevendo código. Agora chegou o momento de falar sobre isso. Toda semana reunimos profissionais da tecnologia para discutir sobre tudo que circula na órbita da programação.</p><p>O Faladev é um podcast original Rocketseat.</p>', 10);






